<?hh // strict
/*
 *  Copyright (c) 2004-present, Facebook, Inc.
 *  All rights reserved.
 *
 *  This source code is licensed under the BSD-style license found in the
 *  LICENSE file in the root directory of this source tree. An additional grant
 *  of patent rights can be found in the PATENTS file in the same directory.
 *
 */

namespace HHVM\UserDocumentation;

// TODO: make this generated by a script; script should also update
// composer, Dockerfile, and Travis configurations
const dict<APIProduct, string> PRODUCT_TAGS = dict[
  APIProduct::HACK => 'HHVM-4.4.0',
  APIProduct::HSL => 'v4.1.0',
];
